"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import * as AlertDialog from "@radix-ui/react-alert-dialog";
import * as Dialog from "@radix-ui/react-dialog";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { Archive, Check, ChevronRight, Copy, FileText, Folder, LoaderCircle, MoreHorizontal, Palette, Pencil, Plus, RotateCcw, Star, Trash2, UserPlus, X } from "lucide-react";
import { archivePageAction, archiveSpaceAction, createPageAction, duplicatePageAction, duplicateSpaceAction, permanentlyDeletePageAction, permanentlyDeleteSpaceAction, restorePageAction, restoreSpaceAction, setPageFavoriteAction, updateSpaceAction } from "@/app/spaces/actions";
import { formatRelativeTime, PAGE_TEMPLATE_LABELS, PAGE_TEMPLATES, SPACE_COLORS, type PageTemplate, type SpaceColor, type SpaceDetail, type SpacePage, type SpaceSummary } from "@/lib/spaces-domain";
import { SpaceCollaborationPanel } from "@/components/spaces/page-collaboration";

type PageMode = "active" | "favorites" | "archived";
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const messageOf = (error: unknown) => error instanceof Error ? error.message : "Something went wrong.";

export function SpacePageList({ initialSpace, activeSpaces }: { initialSpace: SpaceDetail; activeSpaces: SpaceSummary[] }) {
  const router = useRouter();
  const [space, setSpace] = useState(initialSpace);
  const [mode, setMode] = useState<PageMode>(initialSpace.archivedAt ? "archived" : "active");
  const [pageDialog, setPageDialog] = useState(false);
  const [editSpace, setEditSpace] = useState(false);
  const [collabOpen, setCollabOpen] = useState(false);
  const [deletePage, setDeletePage] = useState<SpacePage | null>(null);
  const [deleteSpace, setDeleteSpace] = useState(false);
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const visible = useMemo(() => space.pages.filter((page) => mode === "archived" ? Boolean(page.archivedAt) : !page.archivedAt && (mode === "favorites" ? page.isFavorite : true)), [mode, space.pages]);
  const activeCount = space.pages.filter((page) => !page.archivedAt).length;

  const mutate = (action: () => Promise<void>) => { setMessage(""); startTransition(() => void action().catch((error) => setMessage(messageOf(error)))); };
  const patchPage = (id: number, values: Partial<SpacePage>) => setSpace((current) => ({ ...current, pages: current.pages.map((page) => page.id === id ? { ...page, ...values } : page) }));

  return <div className="space-pages-view" style={{ "--space-color": space.color } as React.CSSProperties}>
    {message && <div className="spaces-toast" role="status">{message}<button onClick={() => setMessage("")} aria-label="Dismiss"><X size={14} /></button></div>}
    {space.archivedAt && <div className="space-archived-banner"><Archive size={14} /> This space is archived. Restore it to create or edit pages.</div>}
    <header className="space-detail-head">
      <div><div className="space-breadcrumb"><Link href="/spaces">All Spaces</Link><ChevronRight size={13} /><span>{space.name}</span></div><div className="space-title-line"><span><Folder size={23} fill="currentColor" /></span><div><h1>{space.name}</h1><p>{activeCount} {activeCount === 1 ? "page" : "pages"}{space.description ? ` · ${space.description}` : ""}</p></div></div></div>
      <div className="space-head-actions">{!space.archivedAt && <button className="spaces-primary" onClick={() => setPageDialog(true)}><Plus size={15} /> New Page</button>}<SpaceMenu space={space} invite={() => setCollabOpen(true)} add={() => setPageDialog(true)} edit={() => setEditSpace(true)} mutate={mutate} archived={() => setSpace((current) => ({ ...current, archivedAt: new Date().toISOString(), isFavorite: false }))} restored={() => { setSpace((current) => ({ ...current, archivedAt: null })); setMode("active"); }} remove={() => setDeleteSpace(true)} router={router} /></div>
    </header>
    <nav className="page-tabs" aria-label="Page filters"><button className={mode === "active" ? "active" : ""} onClick={() => setMode("active")}><FileText size={13} />Active <small>{activeCount}</small></button><button className={mode === "favorites" ? "active" : ""} onClick={() => setMode("favorites")}><Star size={13} />Favorites <small>{space.pages.filter((page) => !page.archivedAt && page.isFavorite).length}</small></button><button className={mode === "archived" ? "active" : ""} onClick={() => setMode("archived")}><Archive size={13} />Archived <small>{space.pages.filter((page) => page.archivedAt).length}</small></button></nav>

    {visible.length ? <div className="pages-table-wrap"><table className="pages-table"><thead><tr><th>Page Name</th><th>Type / Template</th><th>Last Updated</th><th>Updated By</th><th><span className="sr-only">Favorite</span></th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map((page) => <tr key={page.id}>
      <td><Link href={`/spaces/${space.id}/pages/${page.id}`}><span className="page-file-icon"><FileText size={14} /></span><strong>{page.title}</strong></Link></td><td><span className="page-type-badge">{PAGE_TEMPLATE_LABELS[page.template]}</span></td><td>Updated {formatRelativeTime(page.updatedAt)}</td><td><span className="page-updater" title={page.updatedBy.email}>{page.updatedBy.imageUrl ? <img src={page.updatedBy.imageUrl} alt="" /> : initials(page.updatedBy.name)}</span><span>{page.updatedBy.name}</span></td><td><button className={`page-favorite ${page.isFavorite ? "active" : ""}`} disabled={Boolean(page.archivedAt)} aria-label={page.isFavorite ? "Remove favorite" : "Add favorite"} onClick={() => mutate(async () => { await setPageFavoriteAction(page.id, !page.isFavorite); patchPage(page.id, { isFavorite: !page.isFavorite }); })}><Star size={14} fill={page.isFavorite ? "currentColor" : "none"} /></button></td><td><PageRowMenu page={page} mutate={mutate} patch={patchPage} duplicate={async () => { const copy = await duplicatePageAction(page.id); router.push(`/spaces/${copy.spaceId}/pages/${copy.pageId}`); }} remove={() => setDeletePage(page)} /></td>
    </tr>)}</tbody></table></div> : <div className="pages-empty"><span><FileText size={26} /></span><h2>{mode === "active" ? "No pages in this space" : mode === "favorites" ? "No favorite pages" : "No archived pages"}</h2><p>{mode === "active" ? "Create a page from a template or start with a blank document." : "Pages will appear here when they match this view."}</p>{mode === "active" && !space.archivedAt && <button onClick={() => setPageDialog(true)}><Plus size={14} /> Create Page</button>}</div>}

    <CreatePageDialog open={pageDialog} pending={pending} currentSpaceId={space.id} spaces={activeSpaces} close={() => !pending && setPageDialog(false)} create={(input) => mutate(async () => { const page = await createPageAction(input); setPageDialog(false); router.push(`/spaces/${page.spaceId}/pages/${page.pageId}`); })} />
    <EditSpaceDialog open={editSpace} pending={pending} space={space} close={() => !pending && setEditSpace(false)} save={(draft) => mutate(async () => { await updateSpaceAction(space.id, draft); setSpace((current) => ({ ...current, ...draft })); setEditSpace(false); router.refresh(); })} />
    {collabOpen && <SpaceCollaborationPanel spaceId={space.id} isOwner={space.accessRole === "owner"} close={() => setCollabOpen(false)} />}
    <AlertDialog.Root open={Boolean(deletePage)} onOpenChange={(open) => !open && setDeletePage(null)}><AlertDialog.Portal><AlertDialog.Overlay className="spaces-dialog-overlay" /><AlertDialog.Content className="spaces-alert"><span className="danger-icon"><Trash2 size={19} /></span><AlertDialog.Title>Delete “{deletePage?.title}” permanently?</AlertDialog.Title><AlertDialog.Description>This document and its content cannot be recovered.</AlertDialog.Description><div><AlertDialog.Cancel>Cancel</AlertDialog.Cancel><AlertDialog.Action onClick={() => deletePage && mutate(async () => { await permanentlyDeletePageAction(deletePage.id); setSpace((current) => ({ ...current, pages: current.pages.filter((page) => page.id !== deletePage.id) })); setDeletePage(null); })}>Delete page</AlertDialog.Action></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>
    <AlertDialog.Root open={deleteSpace} onOpenChange={setDeleteSpace}><AlertDialog.Portal><AlertDialog.Overlay className="spaces-dialog-overlay" /><AlertDialog.Content className="spaces-alert"><span className="danger-icon"><Trash2 size={19} /></span><AlertDialog.Title>Delete “{space.name}” permanently?</AlertDialog.Title><AlertDialog.Description>Every page in this space will be deleted. This cannot be undone.</AlertDialog.Description><div><AlertDialog.Cancel>Cancel</AlertDialog.Cancel><AlertDialog.Action onClick={() => mutate(async () => { await permanentlyDeleteSpaceAction(space.id); router.push("/spaces"); })}>Delete space</AlertDialog.Action></div></AlertDialog.Content></AlertDialog.Portal></AlertDialog.Root>
  </div>;
}

function PageRowMenu({ page, mutate, patch, duplicate, remove }: { page: SpacePage; mutate: (task: () => Promise<void>) => void; patch: (id: number, values: Partial<SpacePage>) => void; duplicate: () => Promise<void>; remove: () => void }) {
  return <DropdownMenu.Root><DropdownMenu.Trigger asChild><button className="page-more" aria-label={`Actions for ${page.title}`}><MoreHorizontal size={16} /></button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="spaces-menu" align="end" sideOffset={5}>{!page.archivedAt ? <><DropdownMenu.Item onSelect={() => void duplicate()}><Copy size={13} /> Duplicate</DropdownMenu.Item><DropdownMenu.Item onSelect={() => mutate(async () => { await archivePageAction(page.id); patch(page.id, { archivedAt: new Date().toISOString(), isFavorite: false }); })}><Archive size={13} /> Archive</DropdownMenu.Item></> : <><DropdownMenu.Item onSelect={() => mutate(async () => { await restorePageAction(page.id); patch(page.id, { archivedAt: null }); })}><RotateCcw size={13} /> Restore</DropdownMenu.Item><DropdownMenu.Item className="danger" onSelect={remove}><Trash2 size={13} /> Delete permanently</DropdownMenu.Item></>}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>;
}

function SpaceMenu({ space, invite, add, edit, mutate, archived, restored, remove, router }: { space: SpaceDetail; invite: () => void; add: () => void; edit: () => void; mutate: (task: () => Promise<void>) => void; archived: () => void; restored: () => void; remove: () => void; router: ReturnType<typeof useRouter> }) {
  return <DropdownMenu.Root><DropdownMenu.Trigger asChild><button className="space-more-button" aria-label="Space actions"><MoreHorizontal size={18} /></button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="spaces-menu" align="end" sideOffset={5}>{!space.archivedAt ? <>{space.accessRole === "owner" && <><DropdownMenu.Item onSelect={edit}><Pencil size={13} /> Rename Space</DropdownMenu.Item><DropdownMenu.Item onSelect={edit}><Palette size={13} /> Change Color</DropdownMenu.Item></>}<DropdownMenu.Item onSelect={add}><Plus size={13} /> Add Page</DropdownMenu.Item><DropdownMenu.Item onSelect={() => mutate(async () => { const id = await duplicateSpaceAction(space.id); router.push(`/spaces/${id}`); })}><Copy size={13} /> Duplicate</DropdownMenu.Item><DropdownMenu.Item onSelect={invite}><UserPlus size={13} /> {space.accessRole === "owner" ? "Invite Collaborators" : "View Collaborators"}</DropdownMenu.Item>{space.accessRole === "owner" && <DropdownMenu.Item onSelect={() => mutate(async () => { await archiveSpaceAction(space.id); archived(); })}><Archive size={13} /> Archive</DropdownMenu.Item>}</> : <>{space.accessRole === "owner" && <><DropdownMenu.Item onSelect={() => mutate(async () => { await restoreSpaceAction(space.id); restored(); })}><RotateCcw size={13} /> Restore Space</DropdownMenu.Item><DropdownMenu.Item className="danger" onSelect={remove}><Trash2 size={13} /> Delete permanently</DropdownMenu.Item></>}</>}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>;
}

function CreatePageDialog({ open, pending, currentSpaceId, spaces, close, create }: { open: boolean; pending: boolean; currentSpaceId: number; spaces: SpaceSummary[]; close: () => void; create: (input: { title: string; template: PageTemplate; spaceId: number }) => void }) {
  const [title, setTitle] = useState(""); const [template, setTemplate] = useState<PageTemplate>("blank"); const [spaceId, setSpaceId] = useState(currentSpaceId);
  return <Dialog.Root open={open} onOpenChange={(value) => !value && close()}><Dialog.Portal><Dialog.Overlay className="spaces-dialog-overlay" /><Dialog.Content className="spaces-dialog page-create-dialog"><div className="spaces-dialog-heading"><span><FileText size={19} /></span><div><Dialog.Title>Create New Page</Dialog.Title><Dialog.Description>Choose a home and a useful starting point.</Dialog.Description></div><Dialog.Close disabled={pending}><X size={17} /></Dialog.Close></div><form onSubmit={(event) => { event.preventDefault(); create({ title, template, spaceId }); }}><label><span>Page Name</span><input autoFocus required maxLength={160} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Q2 Roadmap" /></label><label><span>Add to Space</span><select value={spaceId} onChange={(event) => setSpaceId(Number(event.target.value))}>{spaces.map((space) => <option value={space.id} key={space.id}>{space.name}</option>)}</select></label><label><span>Template</span><select value={template} onChange={(event) => setTemplate(event.target.value as PageTemplate)}>{PAGE_TEMPLATES.map((value) => <option value={value} key={value}>{PAGE_TEMPLATE_LABELS[value]}</option>)}</select></label><div className="template-preview"><FileText size={16} /><div><strong>{PAGE_TEMPLATE_LABELS[template]}</strong><span>{template === "blank" ? "A clean document ready for your ideas." : "Creates editable headings and prompts to help you begin."}</span></div></div><div className="spaces-dialog-footer"><button type="button" className="secondary" onClick={close}>Cancel</button><button type="submit" disabled={pending || !title.trim()}>{pending && <LoaderCircle className="spin" size={14} />}{pending ? "Creating…" : "Create Page"}</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function EditSpaceDialog({ open, pending, space, close, save }: { open: boolean; pending: boolean; space: SpaceDetail; close: () => void; save: (draft: { name: string; description: string; color: SpaceColor }) => void }) {
  const [name, setName] = useState(space.name); const [description, setDescription] = useState(space.description); const [color, setColor] = useState<SpaceColor>(space.color);
  return <Dialog.Root open={open} onOpenChange={(value) => !value && close()}><Dialog.Portal><Dialog.Overlay className="spaces-dialog-overlay" /><Dialog.Content className="spaces-dialog"><div className="spaces-dialog-heading"><span><Folder size={19} /></span><div><Dialog.Title>Edit Space</Dialog.Title><Dialog.Description>Update this space’s details.</Dialog.Description></div><Dialog.Close disabled={pending}><X size={17} /></Dialog.Close></div><form onSubmit={(event) => { event.preventDefault(); save({ name, description, color }); }}><label><span>Space Name</span><input required maxLength={160} value={name} onChange={(event) => setName(event.target.value)} /></label><label><span>Description <small>Optional</small></span><textarea maxLength={500} value={description} onChange={(event) => setDescription(event.target.value)} /></label><fieldset><legend>Color</legend><div className="spaces-color-row">{SPACE_COLORS.map((value) => <button type="button" key={value} className={color === value ? "active" : ""} style={{ background: value }} onClick={() => setColor(value)}>{color === value && <Check size={12} />}</button>)}</div></fieldset><div className="spaces-dialog-footer"><button type="button" className="secondary" onClick={close}>Cancel</button><button type="submit" disabled={pending || !name.trim()}>{pending ? "Saving…" : "Save Changes"}</button></div></form></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
