"use client";

import { useCallback, useEffect, useRef, useState } from "react";
export type VoiceAgentStatus = "idle" | "connecting" | "listening" | "error";
type VoiceCallbacks = { onUserTranscript: (text: string) => void; onAgentTranscript: (text: string) => void; onUserPartial?: (text: string) => void; onAgentPartial?: (text: string) => void };
function asBase64(buffer: ArrayBuffer) { let value = ""; for (const byte of new Uint8Array(buffer)) value += String.fromCharCode(byte); return btoa(value); }
export function useVoiceAgent({ onUserTranscript, onAgentTranscript, onUserPartial, onAgentPartial }: VoiceCallbacks) {
  const [status, setStatus] = useState<VoiceAgentStatus>("idle"); const [error, setError] = useState("");
  const socket = useRef<WebSocket | null>(null); const stream = useRef<MediaStream | null>(null); const context = useRef<AudioContext | null>(null); const node = useRef<AudioWorkletNode | null>(null); const sources = useRef(new Set<AudioBufferSourceNode>()); const ready = useRef(false); const playhead = useRef(0); const userPartial = useRef(""); const agentPartial = useRef("");
  const stop = useCallback(() => { ready.current = false; socket.current?.send(JSON.stringify({ type: "session.end" })); socket.current?.close(); socket.current = null; stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; node.current?.disconnect(); node.current = null; void context.current?.close(); context.current = null; sources.current.forEach((source) => source.stop()); sources.current.clear(); setStatus("idle"); }, []);
  useEffect(() => {
    return () => {
      stop();
    };
  }, [stop]);
  const start = useCallback(async () => { if (status !== "idle" && status !== "error") return; setError(""); setStatus("connecting"); try {
    const tokenResponse = await fetch("/api/assistant/voice/token", { method: "POST" }); const tokenData = await tokenResponse.json(); if (!tokenResponse.ok) throw new Error(tokenData.error || "Unable to start voice.");
    const audioContext = new AudioContext({ sampleRate: 24_000 }); await audioContext.resume(); const media = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true }, video: false }); const source = audioContext.createMediaStreamSource(media);
    const processor = `class Capture extends AudioWorkletProcessor { process(inputs) { const input = inputs[0] && inputs[0][0]; if (input) { const data = new Int16Array(input.length); for (let i=0;i<input.length;i++) data[i] = Math.max(-1, Math.min(1, input[i])) * 32767; this.port.postMessage(data.buffer,[data.buffer]); } return true; } } registerProcessor('flowspace-voice-capture', Capture);`;
    await audioContext.audioWorklet.addModule(URL.createObjectURL(new Blob([processor], { type: "text/javascript" }))); const worklet = new AudioWorkletNode(audioContext, "flowspace-voice-capture"); source.connect(worklet); context.current = audioContext; stream.current = media; node.current = worklet;
    const url = new URL("wss://agents.assemblyai.com/v1/ws"); url.searchParams.set("token", tokenData.token); const ws = new WebSocket(url); socket.current = ws;
    worklet.port.onmessage = (event) => { if (ready.current && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify({ type: "input.audio", audio: asBase64(event.data) })); }; ws.onopen = () => ws.send(JSON.stringify({ type: "session.update", session: tokenData.agentId ? { agent_id: tokenData.agentId } : tokenData.session }));
    ws.onmessage = (event) => { const message = JSON.parse(event.data) as { type?: string; text?: string; transcript?: string; data?: string; message?: string }; const transcript = message.text ?? message.transcript; if (message.type === "session.ready") { ready.current = true; playhead.current = audioContext.currentTime; setStatus("listening"); } else if (message.type === "input.speech.started") { agentPartial.current = ""; sources.current.forEach((entry) => entry.stop()); sources.current.clear(); playhead.current = audioContext.currentTime; } else if (message.type === "transcript.user.delta" && transcript) { userPartial.current += transcript; onUserPartial?.(userPartial.current); } else if (message.type === "transcript.agent.delta" && transcript) { agentPartial.current += transcript; onAgentPartial?.(agentPartial.current); } else if (message.type === "transcript.user" && transcript) { userPartial.current = ""; onUserTranscript(transcript); } else if (message.type === "transcript.agent" && transcript) { agentPartial.current = ""; onAgentTranscript(transcript); } else if ((message.type === "session.error" || message.type === "error") && (message.message || transcript)) { setError(message.message || transcript || "Voice session failed."); setStatus("error"); } else if (message.type === "reply.audio" && message.data) { const raw = atob(message.data); const pcm = new Int16Array(raw.length / 2); for (let i=0;i<pcm.length;i++) pcm[i] = raw.charCodeAt(i*2) | (raw.charCodeAt(i*2+1) << 8); const buffer = audioContext.createBuffer(1, pcm.length, 24_000); const channel = buffer.getChannelData(0); for (let i=0;i<pcm.length;i++) channel[i] = pcm[i] / 32768; const audio = audioContext.createBufferSource(); audio.buffer = buffer; audio.connect(audioContext.destination); const startAt = Math.max(audioContext.currentTime, playhead.current); audio.start(startAt); playhead.current = startAt + buffer.duration; sources.current.add(audio); audio.onended = () => sources.current.delete(audio); } };
    ws.onclose = () => { if (socket.current === ws) stop(); };
  } catch (voiceError) { setError(voiceError instanceof Error ? voiceError.message : "Unable to start voice."); setStatus("error"); } }, [onAgentTranscript, onUserTranscript, status, stop]);
  return { status, error, start, stop };
}
