import Link from "next/link";
import { ArrowUpRight, Bot, Check, Clock3, FileText, MoreHorizontal, MousePointer2, Plus, Sparkles, SquareKanban, StickyNote, Users } from "lucide-react";

const tasks = [
  { title: "Finalize Q3 product roadmap", project: "Flowspace", time: "10:00 AM", color: "violet" },
  { title: "Review new dashboard concepts", project: "Design", time: "1:30 PM", color: "orange" },
  { title: "Team async check-in", project: "Weekly", time: "3:00 PM", color: "green" },
];
const activity = [
  { initials: "MK", name: "Maya", action: "commented on", item: "Homepage concepts", time: "8m", tone: "peach" },
  { initials: "JL", name: "Jon", action: "completed", item: "User interviews", time: "42m", tone: "blue" },
  { initials: "AI", name: "Flow AI", action: "created a summary in", item: "Research", time: "1h", tone: "violet" },
];

export function DashboardContent() {
  return <div className="dashboard-content">
    <section className="welcome-row"><div className="hero-glow hero-glow-one" /><div className="hero-glow hero-glow-two" /><div className="welcome-copy"><p className="eyebrow">SUNDAY, JULY 19 <i /> YOUR DAY AT A GLANCE</p><h1>Good morning, Avery <span>✦</span></h1><p>Everything is moving beautifully. Let’s make today count.</p><div className="welcome-pills"><span><Check size={12} /> 3 tasks today</span><span><Users size={12} /> 3 teammates online</span></div></div><div className="hero-side"><div className="focus-score"><div className="score-ring"><span>78<small>%</small></span></div><div><strong>Weekly rhythm</strong><small><i>↗ 12%</i> from last week</small></div></div><div className="member-stack"><span>MK</span><span>JL</span><span>SA</span><button aria-label="Invite a teammate"><Plus size={14} /></button></div></div></section>
    <section className="quick-grid" aria-label="Quick actions"><Link className="quick-card purple" href="/notes"><span><StickyNote size={18} /></span><div><strong>New note</strong><small>Capture an idea</small></div><Plus size={15} /></Link><Link className="quick-card blue" href="/whiteboard"><span><MousePointer2 size={18} /></span><div><strong>New whiteboard</strong><small>Map it visually</small></div><Plus size={15} /></Link><Link className="quick-card orange" href="/kanban"><span><SquareKanban size={18} /></span><div><strong>New task</strong><small>Plan your next step</small></div><Plus size={15} /></Link><Link className="quick-card green" href="/ai-template-builder"><span><Bot size={18} /></span><div><strong>Build with Flow AI</strong><small>Create a mini app</small></div><Sparkles size={15} /></Link></section>
    <section className="ai-brief"><div className="ai-brief-icon"><Sparkles size={17} /></div><div><span>FLOW AI SUGGESTION</span><strong>Turn your workflow into a focused mini app</strong></div><Link href="/ai-template-builder">Make it happen <ArrowUpRight size={14} /></Link></section>
    <div className="dashboard-grid"><section className="panel focus-panel"><div className="panel-heading"><div><span className="heading-icon violet-bg"><Check size={16} /></span><div><h2>Today’s focus</h2><p>3 tasks on your plate</p></div></div><Link href="/kanban">View all <ArrowUpRight size={14} /></Link></div><div className="task-list">{tasks.map((task, index) => <div className="task-row" key={task.title}><button className={`task-check ${index === 2 ? "done" : ""}`}>{index === 2 && <Check size={12} />}</button><div className={index === 2 ? "completed-task" : ""}><strong>{task.title}</strong><span><i className={task.color} />{task.project}</span></div><time><Clock3 size={13} />{task.time}</time><button className="more-button"><MoreHorizontal size={17} /></button></div>)}</div><Link className="add-task" href="/kanban"><Plus size={15} /> Add a task</Link></section>
      <section className="panel activity-panel"><div className="panel-heading"><div><span className="heading-icon peach-bg"><Users size={16} /></span><div><h2>Recent activity</h2><p>Across your workspace</p></div></div><button><MoreHorizontal size={18} /></button></div><div className="activity-list">{activity.map((entry) => <div className="activity-row" key={entry.name}><span className={`activity-avatar ${entry.tone}`}>{entry.initials}</span><p><strong>{entry.name}</strong> {entry.action} <b>{entry.item}</b><small>{entry.time} ago</small></p></div>)}</div><button className="activity-link">See all activity <ArrowUpRight size={14} /></button></section>
      <section className="panel spaces-panel"><div className="panel-heading"><div><span className="heading-icon blue-bg"><FileText size={16} /></span><div><h2>Your spaces</h2><p>Jump back into your work</p></div></div><Link href="/spaces">View all <ArrowUpRight size={14} /></Link></div><div className="space-cards"><article className="space-card lavender"><div><span>🚀</span><button><MoreHorizontal size={16} /></button></div><h3>Product Hub</h3><p>12 pages · Updated 2h ago</p><div className="mini-avatars"><span>MK</span><span>JL</span><i>+3</i></div></article><article className="space-card mint"><div><span>🌿</span><button><MoreHorizontal size={16} /></button></div><h3>Design System</h3><p>8 pages · Updated yesterday</p><div className="mini-avatars"><span>AM</span><span>SA</span><i>+2</i></div></article><Link className="new-space" href="/spaces"><span><Plus size={19} /></span><strong>New space</strong><small>Start something fresh</small></Link></div></section>
    </div>
  </div>;
}
